language: python
env: # These should match the tox env list
    - TOXENV=py26
    - TOXENV=py27
install:
    - pip install coveralls tox --use-mirrors
    - npm install reflect
script: tox
after_success:
    - coveralls
sudo: false
