name: main
on:
  pull_request:
  push:
    branches: [master]
    tags:

jobs:
  main:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - run: python -m pip install --upgrade setuptools pip tox virtualenv
    - run: npm i reflect
    - run: tox -e py
